name: mentor_square_v3_responsive
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  connectivity_plus: ^6.0.3
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_secure_storage: ^9.2.1
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  meta: ^1.11.0
  syncfusion_flutter_charts: ^25.2.6
  syncfusion_flutter_datagrid: ^25.2.7

dev_dependencies:
  flutter_lints: null
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/Assets/icons/

  fonts:
    - family: Inter

      fonts:
        - asset: lib/Assets/Fonts/Inter-ExtraBold.ttf

        - asset: lib/Assets/Fonts/Inter-Bold.ttf

        - asset: lib/Assets/Fonts/Inter-Medium.ttf

        - asset: lib/Assets/Fonts/Inter-Regular.ttf

        - asset: lib/Assets/Fonts/Inter-SemiBold.ttf

          style: normal

    - family: Montserrat
      fonts:
        - asset: lib/Assets/Fonts/Montserrat-SemiBold.ttf

        - asset: lib/Assets/Fonts/Montserrat-Medium.ttf

        - asset: lib/Assets/Fonts/Montserrat-Regular.ttf

        - asset: lib/Assets/Fonts/Montserrat-Light.ttf

          style: normal
